# Generated by Django 5.1.1 on 2024-09-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphabookapp', '0002_remove_user_register_user_cpassword_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='book_cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
