# Generated by Django 5.1.1 on 2024-09-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphabookapp', '0003_cart_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='book_cover',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
