# Generated by Django 5.1.1 on 2024-09-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphabookapp', '0009_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='book_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
