# Generated by Django 5.1.1 on 2024-09-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alphabookapp', '0010_alter_cart_book_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
